# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 831b640ff55e600f9c76c51f12d5451500241656619159dbe4e3507a87f123726c88e233808178734a93d33317f4c21c3c2d355a440a9c22f889bade545bef3f

test:
  secret_key_base: 2f002f33d1f0852d7b40e23667f41da4c065f455570247265cf66d23c64bf7fd5a824d83da50c44c0e6e3af5a2a6dfec9eac37c6cebad45773932de5150bb964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
